return {
  version = "1.9",
  luaversion = "5.1",
  tiledversion = "1.9.2",
  class = "",
  orientation = "orthogonal",
  renderorder = "right-down",
  width = 26,
  height = 20,
  tilewidth = 64,
  tileheight = 64,
  nextlayerid = 9,
  nextobjectid = 482,
  properties = {},
  tilesets = {},
  layers = {
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 26,
      height = 20,
      id = 1,
      name = "Tile Layer 1",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      encoding = "lua",
      data = {
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 6,
      name = "aliens2",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 437,
          name = "",
          class = "",
          shape = "rectangle",
          x = 192,
          y = 256,
          width = 64,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 438,
          name = "",
          class = "",
          shape = "rectangle",
          x = 320,
          y = 256,
          width = 64,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 439,
          name = "",
          class = "",
          shape = "rectangle",
          x = 448,
          y = 256,
          width = 64,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 440,
          name = "",
          class = "",
          shape = "rectangle",
          x = 576,
          y = 256,
          width = 64,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 441,
          name = "",
          class = "",
          shape = "rectangle",
          x = 704,
          y = 256,
          width = 64,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 442,
          name = "",
          class = "",
          shape = "rectangle",
          x = 832,
          y = 256,
          width = 64,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 443,
          name = "",
          class = "",
          shape = "rectangle",
          x = 960,
          y = 256,
          width = 64,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 444,
          name = "",
          class = "",
          shape = "rectangle",
          x = 1088,
          y = 256,
          width = 64,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 445,
          name = "",
          class = "",
          shape = "rectangle",
          x = 1216,
          y = 256,
          width = 64,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 446,
          name = "",
          class = "",
          shape = "rectangle",
          x = 1344,
          y = 256,
          width = 64,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 447,
          name = "",
          class = "",
          shape = "rectangle",
          x = 1472,
          y = 256,
          width = 64,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 448,
          name = "",
          class = "",
          shape = "rectangle",
          x = 1472,
          y = 384,
          width = 64,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 449,
          name = "",
          class = "",
          shape = "rectangle",
          x = 1344,
          y = 384,
          width = 64,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 450,
          name = "",
          class = "",
          shape = "rectangle",
          x = 1216,
          y = 384,
          width = 64,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 451,
          name = "",
          class = "",
          shape = "rectangle",
          x = 1088,
          y = 384,
          width = 64,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 452,
          name = "",
          class = "",
          shape = "rectangle",
          x = 960,
          y = 384,
          width = 64,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 453,
          name = "",
          class = "",
          shape = "rectangle",
          x = 832,
          y = 384,
          width = 64,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 454,
          name = "",
          class = "",
          shape = "rectangle",
          x = 704,
          y = 384,
          width = 64,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 455,
          name = "",
          class = "",
          shape = "rectangle",
          x = 576,
          y = 384,
          width = 64,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 456,
          name = "",
          class = "",
          shape = "rectangle",
          x = 448,
          y = 384,
          width = 64,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 457,
          name = "",
          class = "",
          shape = "rectangle",
          x = 320,
          y = 384,
          width = 64,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 458,
          name = "",
          class = "",
          shape = "rectangle",
          x = 192,
          y = 384,
          width = 64,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 8,
      name = "aliens3",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 459,
          name = "",
          class = "",
          shape = "rectangle",
          x = 192,
          y = 512,
          width = 64,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 460,
          name = "",
          class = "",
          shape = "rectangle",
          x = 320,
          y = 512,
          width = 64,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 461,
          name = "",
          class = "",
          shape = "rectangle",
          x = 448,
          y = 512,
          width = 64,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 462,
          name = "",
          class = "",
          shape = "rectangle",
          x = 576,
          y = 512,
          width = 64,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 463,
          name = "",
          class = "",
          shape = "rectangle",
          x = 704,
          y = 512,
          width = 64,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 464,
          name = "",
          class = "",
          shape = "rectangle",
          x = 832,
          y = 512,
          width = 64,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 465,
          name = "",
          class = "",
          shape = "rectangle",
          x = 960,
          y = 512,
          width = 64,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 466,
          name = "",
          class = "",
          shape = "rectangle",
          x = 1088,
          y = 512,
          width = 64,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 467,
          name = "",
          class = "",
          shape = "rectangle",
          x = 1216,
          y = 512,
          width = 64,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 468,
          name = "",
          class = "",
          shape = "rectangle",
          x = 1344,
          y = 512,
          width = 64,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 469,
          name = "",
          class = "",
          shape = "rectangle",
          x = 1472,
          y = 512,
          width = 64,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 471,
          name = "",
          class = "",
          shape = "rectangle",
          x = 1472,
          y = 640,
          width = 64,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 472,
          name = "",
          class = "",
          shape = "rectangle",
          x = 1344,
          y = 640,
          width = 64,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 473,
          name = "",
          class = "",
          shape = "rectangle",
          x = 1216,
          y = 640,
          width = 64,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 474,
          name = "",
          class = "",
          shape = "rectangle",
          x = 1088,
          y = 640,
          width = 64,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 475,
          name = "",
          class = "",
          shape = "rectangle",
          x = 960,
          y = 640,
          width = 64,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 476,
          name = "",
          class = "",
          shape = "rectangle",
          x = 832,
          y = 640,
          width = 64,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 477,
          name = "",
          class = "",
          shape = "rectangle",
          x = 704,
          y = 640,
          width = 64,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 478,
          name = "",
          class = "",
          shape = "rectangle",
          x = 576,
          y = 640,
          width = 64,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 479,
          name = "",
          class = "",
          shape = "rectangle",
          x = 448,
          y = 640,
          width = 64,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 480,
          name = "",
          class = "",
          shape = "rectangle",
          x = 320,
          y = 640,
          width = 64,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 481,
          name = "",
          class = "",
          shape = "rectangle",
          x = 192,
          y = 640,
          width = 64,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 5,
      name = "aliens1",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 425,
          name = "",
          class = "",
          shape = "rectangle",
          x = 192,
          y = 128,
          width = 64,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 426,
          name = "",
          class = "",
          shape = "rectangle",
          x = 320,
          y = 128,
          width = 64,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 427,
          name = "",
          class = "",
          shape = "rectangle",
          x = 448,
          y = 128,
          width = 64,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 428,
          name = "",
          class = "",
          shape = "rectangle",
          x = 576,
          y = 128,
          width = 64,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 429,
          name = "",
          class = "",
          shape = "rectangle",
          x = 704,
          y = 128,
          width = 64,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 430,
          name = "",
          class = "",
          shape = "rectangle",
          x = 832,
          y = 128,
          width = 64,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 431,
          name = "",
          class = "",
          shape = "rectangle",
          x = 960,
          y = 128,
          width = 64,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 432,
          name = "",
          class = "",
          shape = "rectangle",
          x = 1088,
          y = 128,
          width = 64,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 433,
          name = "",
          class = "",
          shape = "rectangle",
          x = 1216,
          y = 128,
          width = 64,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 434,
          name = "",
          class = "",
          shape = "rectangle",
          x = 1344,
          y = 128,
          width = 64,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 435,
          name = "",
          class = "",
          shape = "rectangle",
          x = 1472,
          y = 128,
          width = 64,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 3,
      name = "player",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 83,
          name = "",
          class = "",
          shape = "rectangle",
          x = 832,
          y = 1152,
          width = 64,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 4,
      name = "shelters",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 104,
          name = "",
          class = "",
          shape = "rectangle",
          x = 192,
          y = 960,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 106,
          name = "",
          class = "",
          shape = "rectangle",
          x = 288,
          y = 960,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 107,
          name = "",
          class = "",
          shape = "rectangle",
          x = 224,
          y = 960,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 108,
          name = "",
          class = "",
          shape = "rectangle",
          x = 208,
          y = 960,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 109,
          name = "",
          class = "",
          shape = "rectangle",
          x = 256,
          y = 960,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 110,
          name = "",
          class = "",
          shape = "rectangle",
          x = 240,
          y = 960,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 111,
          name = "",
          class = "",
          shape = "rectangle",
          x = 368,
          y = 960,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 112,
          name = "",
          class = "",
          shape = "rectangle",
          x = 192,
          y = 1024,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 113,
          name = "",
          class = "",
          shape = "rectangle",
          x = 192,
          y = 1008,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 114,
          name = "",
          class = "",
          shape = "rectangle",
          x = 192,
          y = 992,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 115,
          name = "",
          class = "",
          shape = "rectangle",
          x = 352,
          y = 960,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 116,
          name = "",
          class = "",
          shape = "rectangle",
          x = 336,
          y = 960,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 117,
          name = "",
          class = "",
          shape = "rectangle",
          x = 320,
          y = 960,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 118,
          name = "",
          class = "",
          shape = "rectangle",
          x = 304,
          y = 960,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 119,
          name = "",
          class = "",
          shape = "rectangle",
          x = 272,
          y = 960,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 120,
          name = "",
          class = "",
          shape = "rectangle",
          x = 192,
          y = 976,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 121,
          name = "",
          class = "",
          shape = "rectangle",
          x = 288,
          y = 976,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 122,
          name = "",
          class = "",
          shape = "rectangle",
          x = 224,
          y = 976,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 123,
          name = "",
          class = "",
          shape = "rectangle",
          x = 208,
          y = 976,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 124,
          name = "",
          class = "",
          shape = "rectangle",
          x = 256,
          y = 976,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 125,
          name = "",
          class = "",
          shape = "rectangle",
          x = 240,
          y = 976,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 126,
          name = "",
          class = "",
          shape = "rectangle",
          x = 368,
          y = 976,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 127,
          name = "",
          class = "",
          shape = "rectangle",
          x = 352,
          y = 976,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 128,
          name = "",
          class = "",
          shape = "rectangle",
          x = 336,
          y = 976,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 129,
          name = "",
          class = "",
          shape = "rectangle",
          x = 320,
          y = 976,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 130,
          name = "",
          class = "",
          shape = "rectangle",
          x = 304,
          y = 976,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 131,
          name = "",
          class = "",
          shape = "rectangle",
          x = 272,
          y = 976,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 132,
          name = "",
          class = "",
          shape = "rectangle",
          x = 192,
          y = 1056,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 133,
          name = "",
          class = "",
          shape = "rectangle",
          x = 192,
          y = 1040,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 134,
          name = "",
          class = "",
          shape = "rectangle",
          x = 192,
          y = 1024,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 135,
          name = "",
          class = "",
          shape = "rectangle",
          x = 192,
          y = 1072,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 136,
          name = "",
          class = "",
          shape = "rectangle",
          x = 208,
          y = 1024,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 137,
          name = "",
          class = "",
          shape = "rectangle",
          x = 208,
          y = 1008,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 138,
          name = "",
          class = "",
          shape = "rectangle",
          x = 208,
          y = 992,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 139,
          name = "",
          class = "",
          shape = "rectangle",
          x = 208,
          y = 1056,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 140,
          name = "",
          class = "",
          shape = "rectangle",
          x = 208,
          y = 1040,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 141,
          name = "",
          class = "",
          shape = "rectangle",
          x = 208,
          y = 1024,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 142,
          name = "",
          class = "",
          shape = "rectangle",
          x = 208,
          y = 1072,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 143,
          name = "",
          class = "",
          shape = "rectangle",
          x = 352,
          y = 1024,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 144,
          name = "",
          class = "",
          shape = "rectangle",
          x = 352,
          y = 1008,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 145,
          name = "",
          class = "",
          shape = "rectangle",
          x = 352,
          y = 992,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 146,
          name = "",
          class = "",
          shape = "rectangle",
          x = 352,
          y = 1056,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 147,
          name = "",
          class = "",
          shape = "rectangle",
          x = 352,
          y = 1040,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 148,
          name = "",
          class = "",
          shape = "rectangle",
          x = 352,
          y = 1024,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 149,
          name = "",
          class = "",
          shape = "rectangle",
          x = 352,
          y = 1072,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 150,
          name = "",
          class = "",
          shape = "rectangle",
          x = 368,
          y = 1024,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 151,
          name = "",
          class = "",
          shape = "rectangle",
          x = 368,
          y = 1008,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 152,
          name = "",
          class = "",
          shape = "rectangle",
          x = 368,
          y = 992,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 153,
          name = "",
          class = "",
          shape = "rectangle",
          x = 368,
          y = 1056,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 154,
          name = "",
          class = "",
          shape = "rectangle",
          x = 368,
          y = 1040,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 155,
          name = "",
          class = "",
          shape = "rectangle",
          x = 368,
          y = 1024,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 156,
          name = "",
          class = "",
          shape = "rectangle",
          x = 368,
          y = 1072,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 157,
          name = "",
          class = "",
          shape = "rectangle",
          x = 256,
          y = 992,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 158,
          name = "",
          class = "",
          shape = "rectangle",
          x = 224,
          y = 992,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 159,
          name = "",
          class = "",
          shape = "rectangle",
          x = 240,
          y = 992,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 160,
          name = "",
          class = "",
          shape = "rectangle",
          x = 336,
          y = 992,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 161,
          name = "",
          class = "",
          shape = "rectangle",
          x = 304,
          y = 992,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 162,
          name = "",
          class = "",
          shape = "rectangle",
          x = 320,
          y = 992,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 163,
          name = "",
          class = "",
          shape = "rectangle",
          x = 224,
          y = 1008,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 164,
          name = "",
          class = "",
          shape = "rectangle",
          x = 240,
          y = 1008,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 165,
          name = "",
          class = "",
          shape = "rectangle",
          x = 320,
          y = 1008,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 166,
          name = "",
          class = "",
          shape = "rectangle",
          x = 336,
          y = 1008,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 167,
          name = "",
          class = "",
          shape = "rectangle",
          x = 224,
          y = 1024,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 168,
          name = "",
          class = "",
          shape = "rectangle",
          x = 336,
          y = 1024,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 169,
          name = "",
          class = "",
          shape = "rectangle",
          x = 576,
          y = 960,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 170,
          name = "",
          class = "",
          shape = "rectangle",
          x = 672,
          y = 960,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 171,
          name = "",
          class = "",
          shape = "rectangle",
          x = 608,
          y = 960,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 172,
          name = "",
          class = "",
          shape = "rectangle",
          x = 592,
          y = 960,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 173,
          name = "",
          class = "",
          shape = "rectangle",
          x = 640,
          y = 960,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 174,
          name = "",
          class = "",
          shape = "rectangle",
          x = 624,
          y = 960,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 175,
          name = "",
          class = "",
          shape = "rectangle",
          x = 752,
          y = 960,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 176,
          name = "",
          class = "",
          shape = "rectangle",
          x = 576,
          y = 1024,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 177,
          name = "",
          class = "",
          shape = "rectangle",
          x = 576,
          y = 1008,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 178,
          name = "",
          class = "",
          shape = "rectangle",
          x = 576,
          y = 992,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 179,
          name = "",
          class = "",
          shape = "rectangle",
          x = 736,
          y = 960,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 180,
          name = "",
          class = "",
          shape = "rectangle",
          x = 720,
          y = 960,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 181,
          name = "",
          class = "",
          shape = "rectangle",
          x = 704,
          y = 960,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 182,
          name = "",
          class = "",
          shape = "rectangle",
          x = 688,
          y = 960,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 183,
          name = "",
          class = "",
          shape = "rectangle",
          x = 656,
          y = 960,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 184,
          name = "",
          class = "",
          shape = "rectangle",
          x = 576,
          y = 976,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 185,
          name = "",
          class = "",
          shape = "rectangle",
          x = 672,
          y = 976,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 186,
          name = "",
          class = "",
          shape = "rectangle",
          x = 608,
          y = 976,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 187,
          name = "",
          class = "",
          shape = "rectangle",
          x = 592,
          y = 976,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 188,
          name = "",
          class = "",
          shape = "rectangle",
          x = 640,
          y = 976,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 189,
          name = "",
          class = "",
          shape = "rectangle",
          x = 624,
          y = 976,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 190,
          name = "",
          class = "",
          shape = "rectangle",
          x = 752,
          y = 976,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 191,
          name = "",
          class = "",
          shape = "rectangle",
          x = 736,
          y = 976,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 192,
          name = "",
          class = "",
          shape = "rectangle",
          x = 720,
          y = 976,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 193,
          name = "",
          class = "",
          shape = "rectangle",
          x = 704,
          y = 976,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 194,
          name = "",
          class = "",
          shape = "rectangle",
          x = 688,
          y = 976,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 195,
          name = "",
          class = "",
          shape = "rectangle",
          x = 656,
          y = 976,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 196,
          name = "",
          class = "",
          shape = "rectangle",
          x = 576,
          y = 1056,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 197,
          name = "",
          class = "",
          shape = "rectangle",
          x = 576,
          y = 1040,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 198,
          name = "",
          class = "",
          shape = "rectangle",
          x = 576,
          y = 1024,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 199,
          name = "",
          class = "",
          shape = "rectangle",
          x = 576,
          y = 1072,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 200,
          name = "",
          class = "",
          shape = "rectangle",
          x = 592,
          y = 1024,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 201,
          name = "",
          class = "",
          shape = "rectangle",
          x = 592,
          y = 1008,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 202,
          name = "",
          class = "",
          shape = "rectangle",
          x = 592,
          y = 992,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 203,
          name = "",
          class = "",
          shape = "rectangle",
          x = 592,
          y = 1056,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 204,
          name = "",
          class = "",
          shape = "rectangle",
          x = 592,
          y = 1040,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 205,
          name = "",
          class = "",
          shape = "rectangle",
          x = 592,
          y = 1024,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 206,
          name = "",
          class = "",
          shape = "rectangle",
          x = 592,
          y = 1072,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 207,
          name = "",
          class = "",
          shape = "rectangle",
          x = 736,
          y = 1024,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 208,
          name = "",
          class = "",
          shape = "rectangle",
          x = 736,
          y = 1008,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 209,
          name = "",
          class = "",
          shape = "rectangle",
          x = 736,
          y = 992,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 210,
          name = "",
          class = "",
          shape = "rectangle",
          x = 736,
          y = 1056,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 211,
          name = "",
          class = "",
          shape = "rectangle",
          x = 736,
          y = 1040,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 212,
          name = "",
          class = "",
          shape = "rectangle",
          x = 736,
          y = 1024,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 213,
          name = "",
          class = "",
          shape = "rectangle",
          x = 736,
          y = 1072,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 214,
          name = "",
          class = "",
          shape = "rectangle",
          x = 752,
          y = 1024,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 215,
          name = "",
          class = "",
          shape = "rectangle",
          x = 752,
          y = 1008,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 216,
          name = "",
          class = "",
          shape = "rectangle",
          x = 752,
          y = 992,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 217,
          name = "",
          class = "",
          shape = "rectangle",
          x = 752,
          y = 1056,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 218,
          name = "",
          class = "",
          shape = "rectangle",
          x = 752,
          y = 1040,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 219,
          name = "",
          class = "",
          shape = "rectangle",
          x = 752,
          y = 1024,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 220,
          name = "",
          class = "",
          shape = "rectangle",
          x = 752,
          y = 1072,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 221,
          name = "",
          class = "",
          shape = "rectangle",
          x = 640,
          y = 992,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 222,
          name = "",
          class = "",
          shape = "rectangle",
          x = 608,
          y = 992,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 223,
          name = "",
          class = "",
          shape = "rectangle",
          x = 624,
          y = 992,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 224,
          name = "",
          class = "",
          shape = "rectangle",
          x = 720,
          y = 992,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 225,
          name = "",
          class = "",
          shape = "rectangle",
          x = 688,
          y = 992,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 226,
          name = "",
          class = "",
          shape = "rectangle",
          x = 704,
          y = 992,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 227,
          name = "",
          class = "",
          shape = "rectangle",
          x = 608,
          y = 1008,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 228,
          name = "",
          class = "",
          shape = "rectangle",
          x = 624,
          y = 1008,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 229,
          name = "",
          class = "",
          shape = "rectangle",
          x = 704,
          y = 1008,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 230,
          name = "",
          class = "",
          shape = "rectangle",
          x = 720,
          y = 1008,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 231,
          name = "",
          class = "",
          shape = "rectangle",
          x = 608,
          y = 1024,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 232,
          name = "",
          class = "",
          shape = "rectangle",
          x = 720,
          y = 1024,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 233,
          name = "",
          class = "",
          shape = "rectangle",
          x = 960,
          y = 960,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 234,
          name = "",
          class = "",
          shape = "rectangle",
          x = 1056,
          y = 960,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 235,
          name = "",
          class = "",
          shape = "rectangle",
          x = 992,
          y = 960,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 236,
          name = "",
          class = "",
          shape = "rectangle",
          x = 976,
          y = 960,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 237,
          name = "",
          class = "",
          shape = "rectangle",
          x = 1024,
          y = 960,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 238,
          name = "",
          class = "",
          shape = "rectangle",
          x = 1008,
          y = 960,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 239,
          name = "",
          class = "",
          shape = "rectangle",
          x = 1136,
          y = 960,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 240,
          name = "",
          class = "",
          shape = "rectangle",
          x = 960,
          y = 1024,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 241,
          name = "",
          class = "",
          shape = "rectangle",
          x = 960,
          y = 1008,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 242,
          name = "",
          class = "",
          shape = "rectangle",
          x = 960,
          y = 992,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 243,
          name = "",
          class = "",
          shape = "rectangle",
          x = 1120,
          y = 960,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 244,
          name = "",
          class = "",
          shape = "rectangle",
          x = 1104,
          y = 960,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 245,
          name = "",
          class = "",
          shape = "rectangle",
          x = 1088,
          y = 960,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 246,
          name = "",
          class = "",
          shape = "rectangle",
          x = 1072,
          y = 960,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 247,
          name = "",
          class = "",
          shape = "rectangle",
          x = 1040,
          y = 960,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 248,
          name = "",
          class = "",
          shape = "rectangle",
          x = 960,
          y = 976,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 249,
          name = "",
          class = "",
          shape = "rectangle",
          x = 1056,
          y = 976,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 250,
          name = "",
          class = "",
          shape = "rectangle",
          x = 992,
          y = 976,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 251,
          name = "",
          class = "",
          shape = "rectangle",
          x = 976,
          y = 976,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 252,
          name = "",
          class = "",
          shape = "rectangle",
          x = 1024,
          y = 976,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 253,
          name = "",
          class = "",
          shape = "rectangle",
          x = 1008,
          y = 976,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 254,
          name = "",
          class = "",
          shape = "rectangle",
          x = 1136,
          y = 976,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 255,
          name = "",
          class = "",
          shape = "rectangle",
          x = 1120,
          y = 976,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 256,
          name = "",
          class = "",
          shape = "rectangle",
          x = 1104,
          y = 976,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 257,
          name = "",
          class = "",
          shape = "rectangle",
          x = 1088,
          y = 976,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 258,
          name = "",
          class = "",
          shape = "rectangle",
          x = 1072,
          y = 976,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 259,
          name = "",
          class = "",
          shape = "rectangle",
          x = 1040,
          y = 976,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 260,
          name = "",
          class = "",
          shape = "rectangle",
          x = 960,
          y = 1056,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 261,
          name = "",
          class = "",
          shape = "rectangle",
          x = 960,
          y = 1040,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 262,
          name = "",
          class = "",
          shape = "rectangle",
          x = 960,
          y = 1024,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 263,
          name = "",
          class = "",
          shape = "rectangle",
          x = 960,
          y = 1072,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 264,
          name = "",
          class = "",
          shape = "rectangle",
          x = 976,
          y = 1024,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 265,
          name = "",
          class = "",
          shape = "rectangle",
          x = 976,
          y = 1008,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 266,
          name = "",
          class = "",
          shape = "rectangle",
          x = 976,
          y = 992,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 267,
          name = "",
          class = "",
          shape = "rectangle",
          x = 976,
          y = 1056,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 268,
          name = "",
          class = "",
          shape = "rectangle",
          x = 976,
          y = 1040,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 269,
          name = "",
          class = "",
          shape = "rectangle",
          x = 976,
          y = 1024,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 270,
          name = "",
          class = "",
          shape = "rectangle",
          x = 976,
          y = 1072,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 271,
          name = "",
          class = "",
          shape = "rectangle",
          x = 1120,
          y = 1024,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 272,
          name = "",
          class = "",
          shape = "rectangle",
          x = 1120,
          y = 1008,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 273,
          name = "",
          class = "",
          shape = "rectangle",
          x = 1120,
          y = 992,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 274,
          name = "",
          class = "",
          shape = "rectangle",
          x = 1120,
          y = 1056,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 275,
          name = "",
          class = "",
          shape = "rectangle",
          x = 1120,
          y = 1040,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 276,
          name = "",
          class = "",
          shape = "rectangle",
          x = 1120,
          y = 1024,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 277,
          name = "",
          class = "",
          shape = "rectangle",
          x = 1120,
          y = 1072,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 278,
          name = "",
          class = "",
          shape = "rectangle",
          x = 1136,
          y = 1024,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 279,
          name = "",
          class = "",
          shape = "rectangle",
          x = 1136,
          y = 1008,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 280,
          name = "",
          class = "",
          shape = "rectangle",
          x = 1136,
          y = 992,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 281,
          name = "",
          class = "",
          shape = "rectangle",
          x = 1136,
          y = 1056,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 282,
          name = "",
          class = "",
          shape = "rectangle",
          x = 1136,
          y = 1040,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 283,
          name = "",
          class = "",
          shape = "rectangle",
          x = 1136,
          y = 1024,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 284,
          name = "",
          class = "",
          shape = "rectangle",
          x = 1136,
          y = 1072,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 285,
          name = "",
          class = "",
          shape = "rectangle",
          x = 1024,
          y = 992,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 286,
          name = "",
          class = "",
          shape = "rectangle",
          x = 992,
          y = 992,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 287,
          name = "",
          class = "",
          shape = "rectangle",
          x = 1008,
          y = 992,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 288,
          name = "",
          class = "",
          shape = "rectangle",
          x = 1104,
          y = 992,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 289,
          name = "",
          class = "",
          shape = "rectangle",
          x = 1072,
          y = 992,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 290,
          name = "",
          class = "",
          shape = "rectangle",
          x = 1088,
          y = 992,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 291,
          name = "",
          class = "",
          shape = "rectangle",
          x = 992,
          y = 1008,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 292,
          name = "",
          class = "",
          shape = "rectangle",
          x = 1008,
          y = 1008,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 293,
          name = "",
          class = "",
          shape = "rectangle",
          x = 1088,
          y = 1008,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 294,
          name = "",
          class = "",
          shape = "rectangle",
          x = 1104,
          y = 1008,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 295,
          name = "",
          class = "",
          shape = "rectangle",
          x = 992,
          y = 1024,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 296,
          name = "",
          class = "",
          shape = "rectangle",
          x = 1104,
          y = 1024,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 361,
          name = "",
          class = "",
          shape = "rectangle",
          x = 1344,
          y = 960,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 362,
          name = "",
          class = "",
          shape = "rectangle",
          x = 1440,
          y = 960,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 363,
          name = "",
          class = "",
          shape = "rectangle",
          x = 1376,
          y = 960,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 364,
          name = "",
          class = "",
          shape = "rectangle",
          x = 1360,
          y = 960,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 365,
          name = "",
          class = "",
          shape = "rectangle",
          x = 1408,
          y = 960,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 366,
          name = "",
          class = "",
          shape = "rectangle",
          x = 1392,
          y = 960,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 367,
          name = "",
          class = "",
          shape = "rectangle",
          x = 1520,
          y = 960,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 368,
          name = "",
          class = "",
          shape = "rectangle",
          x = 1344,
          y = 1024,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 369,
          name = "",
          class = "",
          shape = "rectangle",
          x = 1344,
          y = 1008,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 370,
          name = "",
          class = "",
          shape = "rectangle",
          x = 1344,
          y = 992,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 371,
          name = "",
          class = "",
          shape = "rectangle",
          x = 1504,
          y = 960,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 372,
          name = "",
          class = "",
          shape = "rectangle",
          x = 1488,
          y = 960,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 373,
          name = "",
          class = "",
          shape = "rectangle",
          x = 1472,
          y = 960,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 374,
          name = "",
          class = "",
          shape = "rectangle",
          x = 1456,
          y = 960,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 375,
          name = "",
          class = "",
          shape = "rectangle",
          x = 1424,
          y = 960,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 376,
          name = "",
          class = "",
          shape = "rectangle",
          x = 1344,
          y = 976,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 377,
          name = "",
          class = "",
          shape = "rectangle",
          x = 1440,
          y = 976,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 378,
          name = "",
          class = "",
          shape = "rectangle",
          x = 1376,
          y = 976,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 379,
          name = "",
          class = "",
          shape = "rectangle",
          x = 1360,
          y = 976,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 380,
          name = "",
          class = "",
          shape = "rectangle",
          x = 1408,
          y = 976,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 381,
          name = "",
          class = "",
          shape = "rectangle",
          x = 1392,
          y = 976,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 382,
          name = "",
          class = "",
          shape = "rectangle",
          x = 1520,
          y = 976,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 383,
          name = "",
          class = "",
          shape = "rectangle",
          x = 1504,
          y = 976,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 384,
          name = "",
          class = "",
          shape = "rectangle",
          x = 1488,
          y = 976,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 385,
          name = "",
          class = "",
          shape = "rectangle",
          x = 1472,
          y = 976,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 386,
          name = "",
          class = "",
          shape = "rectangle",
          x = 1456,
          y = 976,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 387,
          name = "",
          class = "",
          shape = "rectangle",
          x = 1424,
          y = 976,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 388,
          name = "",
          class = "",
          shape = "rectangle",
          x = 1344,
          y = 1056,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 389,
          name = "",
          class = "",
          shape = "rectangle",
          x = 1344,
          y = 1040,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 390,
          name = "",
          class = "",
          shape = "rectangle",
          x = 1344,
          y = 1024,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 391,
          name = "",
          class = "",
          shape = "rectangle",
          x = 1344,
          y = 1072,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 392,
          name = "",
          class = "",
          shape = "rectangle",
          x = 1360,
          y = 1024,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 393,
          name = "",
          class = "",
          shape = "rectangle",
          x = 1360,
          y = 1008,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 394,
          name = "",
          class = "",
          shape = "rectangle",
          x = 1360,
          y = 992,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 395,
          name = "",
          class = "",
          shape = "rectangle",
          x = 1360,
          y = 1056,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 396,
          name = "",
          class = "",
          shape = "rectangle",
          x = 1360,
          y = 1040,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 397,
          name = "",
          class = "",
          shape = "rectangle",
          x = 1360,
          y = 1024,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 398,
          name = "",
          class = "",
          shape = "rectangle",
          x = 1360,
          y = 1072,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 399,
          name = "",
          class = "",
          shape = "rectangle",
          x = 1504,
          y = 1024,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 400,
          name = "",
          class = "",
          shape = "rectangle",
          x = 1504,
          y = 1008,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 401,
          name = "",
          class = "",
          shape = "rectangle",
          x = 1504,
          y = 992,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 402,
          name = "",
          class = "",
          shape = "rectangle",
          x = 1504,
          y = 1056,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 403,
          name = "",
          class = "",
          shape = "rectangle",
          x = 1504,
          y = 1040,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 404,
          name = "",
          class = "",
          shape = "rectangle",
          x = 1504,
          y = 1024,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 405,
          name = "",
          class = "",
          shape = "rectangle",
          x = 1504,
          y = 1072,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 406,
          name = "",
          class = "",
          shape = "rectangle",
          x = 1520,
          y = 1024,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 407,
          name = "",
          class = "",
          shape = "rectangle",
          x = 1520,
          y = 1008,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 408,
          name = "",
          class = "",
          shape = "rectangle",
          x = 1520,
          y = 992,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 409,
          name = "",
          class = "",
          shape = "rectangle",
          x = 1520,
          y = 1056,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 410,
          name = "",
          class = "",
          shape = "rectangle",
          x = 1520,
          y = 1040,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 411,
          name = "",
          class = "",
          shape = "rectangle",
          x = 1520,
          y = 1024,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 412,
          name = "",
          class = "",
          shape = "rectangle",
          x = 1520,
          y = 1072,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 413,
          name = "",
          class = "",
          shape = "rectangle",
          x = 1408,
          y = 992,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 414,
          name = "",
          class = "",
          shape = "rectangle",
          x = 1376,
          y = 992,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 415,
          name = "",
          class = "",
          shape = "rectangle",
          x = 1392,
          y = 992,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 416,
          name = "",
          class = "",
          shape = "rectangle",
          x = 1488,
          y = 992,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 417,
          name = "",
          class = "",
          shape = "rectangle",
          x = 1456,
          y = 992,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 418,
          name = "",
          class = "",
          shape = "rectangle",
          x = 1472,
          y = 992,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 419,
          name = "",
          class = "",
          shape = "rectangle",
          x = 1376,
          y = 1008,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 420,
          name = "",
          class = "",
          shape = "rectangle",
          x = 1392,
          y = 1008,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 421,
          name = "",
          class = "",
          shape = "rectangle",
          x = 1472,
          y = 1008,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 422,
          name = "",
          class = "",
          shape = "rectangle",
          x = 1488,
          y = 1008,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 423,
          name = "",
          class = "",
          shape = "rectangle",
          x = 1376,
          y = 1024,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 424,
          name = "",
          class = "",
          shape = "rectangle",
          x = 1488,
          y = 1024,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    }
  }
}
